# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.4
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test

machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build --rm=false -t mzget/stalk-platform .

test:
  override:
    - docker run --name stalk-platform -p 3020-3021:3020-3021 -d mzget/stalk-platform; sleep 10
    - curl --retry 10 --retry-delay 5 -v ws://localhost:3020

deployment:
  hub:
    branch: master
    commands:
      - docker login -e nattapon.r@live.com -u mzget -p $dockerP@ssw0rd
      - docker push mzget/stalk-platform

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master